// Icons
import { createIcons,
AtSign,
Binary,
BookOpenText,
CirclePlus,
ClipboardCopy,
Facebook,
FileBadge,
FolderCog,
Github,
Globe,
HandCoins,
Info,
Instagram,
Laptop,
Link,
Linkedin,
Mail,
MapPin,
NotebookPen,
Package,
ScrollText,
Search,
Send,
ServerCog,
TriangleAlert,
UserRound
} from 'lucide';

// Create Lucide icons
export function makeIcons() {
    createIcons({
        icons: {
            AtSign,
            Binary,
            BookOpenText,
            CirclePlus,
            ClipboardCopy,
            Facebook,
            FileBadge,
            FolderCog,
            Github,
            Globe,
            HandCoins,
            Info,
            Instagram,
            Laptop,
            Link,
            Linkedin,
            Mail,
            MapPin,
            NotebookPen,
            Package,
            ScrollText,
            Search,
            Send,
            ServerCog,
            TriangleAlert,
            UserRound,
        }
    });
}
